name: pwa_qr_scan_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # riverpod
  flutter_riverpod: ^2.5.1

  # qr
  mobile_scanner: ^4.0.1

  # firebase
  firebase_core: ^2.27.0
  permission_handler: ^11.3.0
  package_info_plus: ^5.0.1
  logger: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
